### ISSUE TITLE
Inversion of condition (?)

### ISSUE THREAD

**Issue by roryyorke** [unageek/graphest#940] opened 2023-05-27 14:52 UTC
This is awesome software, thanks!

I'm running on Ubuntu 20.04.  I didn't realize there was a `docs/build.md`, so I first built `graph` via `cargo build`, which worked fine; I used your instructions to install node etc. and run, and it all works.  ~~Maybe you could put a link to `docs/build.md` in your root README.md?~~ [edit: whoops, now I see there is a link!]

I was experimenting with the logical connectives, and I think something isn't quite right.  This is fine:

![image](https://github.com/unageek/graphest/assets/110974/e803869e-8a23-4362-bda8-2c2d48882c8f)

but when I combine the two expressions with "&&" I get this:

![image](https://github.com/unageek/graphest/assets/110974/80d2def4-97dd-4892-b3b2-c1217d676542)

If I logically invert the first condition I get this:

![image](https://github.com/unageek/graphest/assets/110974/7d924d45-50db-4329-95f1-15a6324666f2)

Am I missing something?

**Comment by unageek** [comment] 2023-05-28 05:47
Thank you for taking the time to build the app and reporting this! Apparently, there is a bug in handling the relation `x ≥ y`. I will investigate it.

**Comment by unageek** [comment] 2023-05-28 15:43
The issue is fixed in the latest `main`. Please try it out.

**Comment by roryyorke** [comment] 2023-05-28 16:24
Looks good to me. I see there was also an issue with my issue report.

![image](https://github.com/unageek/graphest/assets/110974/c367c129-b52f-4b72-9ab1-026b901d91ff)

**Comment by unageek** [comment] 2023-06-02 10:37
Fixed in v1.3.3.

**Closed by unageek** 2023-06-02 10:37 UTC
Labels: bug
